name: Dependency Update

on:
  schedule:
    - cron: '0 0 * * 1' # Every Monday at midnight
  workflow_dispatch:

env:
  NODE_VERSION: '20.x'
  PNPM_VERSION: '8'

jobs:
  update-dependencies:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: ${{ env.PNPM_VERSION }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'pnpm'

      - name: Update dependencies
        run: |
          pnpm update --interactive false
          pnpm audit fix

      - name: Run tests after update
        run: |
          pnpm install
          pnpm test
          pnpm build

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'chore: update dependencies'
          title: 'chore: weekly dependency updates'
          body: |
            ## Weekly Dependency Updates

            This PR contains automatic dependency updates for the week.

            ### Changes
            - Updated npm dependencies to their latest versions
            - Fixed any security vulnerabilities found by `pnpm audit`

            ### Checklist
            - [ ] All tests pass
            - [ ] Build completes successfully
            - [ ] No breaking changes identified

            Please review the changes and merge if everything looks good.
          branch: chore/dependency-updates
          delete-branch: true
